### ISSUE TITLE
Notification text in UI

### ISSUE THREAD

**Issue by xqrdot** [efogdev/mpris-timer#2]
Is it possible to set notification's text in UI? I see that there is an option to set a "default" text.

**Comment by efogdev** [comment]
For now, there's no option to change title and text for the "current" timer with UI. 

The idea is to minimize interaction with the app — usually if you need a named timer that means you will probably need it again, so it makes sense to bind some keyboard shortcut or something like that.

I personally use [this](https://github.com/StorageB/custom-command-toggle) extension for named timers:  

![image](https://github.com/user-attachments/assets/fe640d87-2a11-4c9d-9238-b78465cd6a37)

That + a global shortcut for anonymous timers.

But I agree that it is not ideal; I will think about changes in UI — maybe text/title presets, for example.

**Comment by xqrdot** [comment]
Oh, okay, that `StorageB/custom-command-toggle` is what I'd use too then. Thanks for sharing!

Just as an idea, this is how I imagine this feature to look like. To not disrupt the idea behind keeping it simple, there can be a checkbox in settings or in that main UI to make the title input field visible. 

![New Project](https://github.com/user-attachments/assets/60c8429f-3ecd-465c-97a2-9cd5b3973178)

**Comment by efogdev** [comment]
You can try out [this](https://buildbot.flathub.org/#/builders/6/builds/162949) beta build: 
```shell
flatpak install https://dl.flathub.org/build-repo/146021/io.github.efogdev.mpris-timer.flatpakref
```

![Screenshot From 2024-11-18 13-15-04](https://github.com/user-attachments/assets/ff8e84f6-f678-4be6-ae00-d37f5fa88a18)

**Comment by efogdev** [comment]
The feature is now released
