### ISSUE TITLE
AUR

### ISSUE THREAD

**Issue by omnigenous** [efogdev/mpris-timer#3]
https://aur.archlinux.org/

Please, consider publishing to Arch User Repositories!

**Comment by efogdev** [comment]
It is planned — my setup is actually Arch based

**Comment by efogdev** [comment]
Done

**Comment by omnigenous** [comment]
```
 -> No AUR package found for mpris-timer
```
https://aur.archlinux.org/packages?K=mpris-timer

I guess I have to wait a little for database to sync or something

**Comment by efogdev** [comment]
@omnigenous it's `play-timer` now
