### ISSUE TITLE
Compilation not starting

### ISSUE THREAD

**Issue by claymorwan** [efogdev/mpris-timer#4]
I'm trying to build the app using the command shwon in the readme `go build -pgo default.pgo -tags wayland -ldflags="-s -w" -o ./.bin/app ./cmd/main.go` but it doesn't do anything, just get stuck like this
![Screenshot_20241124_094554](https://github.com/user-attachments/assets/c4521c55-be11-43ef-816f-ee65af900846)

**Comment by efogdev** [comment]
Hi, try to take a look at CPU load by cores —it probably is compiling, it is just that the huge part is actually written in C and compiling C sucks. It takes ~20 min with my 8845HS and I hate that :) But that's only for the first time.

**Comment by efogdev** [comment]
Also note that you will need to compile a new gsettings schema, the app won't launch otherwise:
```shell
sudo cp misc/io.github.efogdev.mpris-timer.gschema.xml /usr/share/glib-2.0/schemas/ && sudo glib-compile-schemas /usr/share/glib-2.0/schemas/
```

I'll probably add that to README

**Comment by claymorwan** [comment]
yep so compiled it, executed that command and it seems to be working thanks, the only weird thing is that it looks laggy in the plasma player but it there with the flatpak too so yea, thanks :3

btw since ur here, can I make this an aur package ?

**Comment by efogdev** [comment]
Sure — see #3 — I've added tag "help is welcome"
Regarding the "laggy" player — it is only 6 fps (30 in GNOME) for Plasma because it flickers otherwise
I don't think it is possible to make it smooth without patching KDE

**Comment by claymorwan** [comment]
O oki, Imma make an aur packages rn , and imma look at the kde thingy, thanks :3
