### ISSUE TITLE
New app icon

### ISSUE THREAD

**Issue by Tuba2** [efogdev/mpris-timer#7]
Hey, it's me, u/dassodocaralho from Reddit!

I finally got some time to work on the icon I promised you.
Sorry for taking this long!

I followed the GNOME HIG and color palette, as we agreed upon.

Anyway, here's the design I came up with (I think it is very self explanatory):
![play-timer-icon-grey-blue](https://github.com/user-attachments/assets/a8e5f680-10ea-43c3-b704-ccfc5e1924c8)

And here is it in context with other GNOME icons:

![Preview](https://github.com/user-attachments/assets/ba6a223c-92ac-4d18-803e-04bfed318f53)

Let me know what you think!
We can also test other color schemes, if you prefer.

As soon as we reach a final version, I can send you a finished SVG file 😉

**Comment by efogdev** [comment]
Hey, thanks a lot! Wonderful. Love the style and the idea, and the color scheme overall.

Just 1 little thing: I don't quite like the white "strip" on bottom, I understand that it's perspective view but in small sizes it looks a bit weird IMO. Hmm or maybe that is just because the minute arrow is too long. Honestly not sure.

Let me know if you have thoughts about that

**Comment by Tuba2** [comment]
I was testing thicker bases when I had another idea and ran with it.

I ended up using the minute hand as the base (or fusing it with the base, whichever way you prefer to describe it).

Take a look at how it turned out:

![play-timer-icon-ponteiro-grosso](https://github.com/user-attachments/assets/5600aeb4-b118-4511-b91a-01d5c11814d8)

![Preview Ponteiro Grosso](https://github.com/user-attachments/assets/9813610a-ea97-4a96-b6d4-13a73176ca37)

I think it looks very nice, very delicate, and I think it fits well with the aesthetic.
What do you think of it? Is it an adequate solution?
Let me know!

**Comment by efogdev** [comment]
Was there any problem with thicker base?

I like this version, I'm actually ready to freeze it as final, however now when I compare these two, I see that the strip was a nice touch 😂

I think it is fair to leave this for you to decide. I will accept whatever you say, but I personally would prefer on w/ the light bottom.

**Comment by Tuba2** [comment]
No problem at all! I just thought the hand-as-base looked cooler hahahaha
Here is it with the thicker light base:

![play-timer-icon-base-grossa](https://github.com/user-attachments/assets/7b891911-8b2d-4946-b36c-f27848283af4)

![Preview Base Grossa](https://github.com/user-attachments/assets/f1a433b1-193c-408f-b94d-c85fcd19123f)

Which one do you prefer?

**Comment by Tuba2** [comment]
I think the hand-as-base one is more scalable and is also a cooler solution, but it is your app, you have to be comfortable with its branding :)

**Comment by efogdev** [comment]
Oh damn that's hard! Ok, let's go with the minute-based™ one. Are you willing to open a PR? So I can mention you as an "official" contributor in the README :)

Also I would love to have both last versions. Maybe I'll use one as an icon and the other as the notification image, who knows. 

Again — thanks a lot!

**Comment by efogdev** [comment]
It is here: https://github.com/efogdev/mpris-timer/tree/main/internal/ui/res

**Comment by Tuba2** [comment]
Great! And don't worry, I'm happy to help!

I can send you both versions, of course, but I'd try to use just one version throughout the whole app experience, to keep the branding more consistent.

I'll open the PR as soon as I come back home!

Then we can work on improving metadata for Flathub, following the guidelines, with brand colors and all, if you are willing. But we can save this discussion for another issue hahaha

**Comment by efogdev** [comment]
So, there's not much of a story here: I've already done everything to match Flathub Quality Guidelines (to show the app on the front page), except for the icon. Now, with the new icon, the only thing to discuss (as I see it) is brand colors, and I'll just take whatever you give me here — I really suck at anything aesthetics-related.

**Comment by efogdev** [comment]
Also yes please, send both versions in PR — something like `icon-alt.svg`
I'll use only the main one for now, it's just that I really want to keep another one and maybe do something with it later :)

**Comment by Tuba2** [comment]
PR created!
See comment about icon resolution in #8.

I'll come up with a few nice options for brand colors and create a new issue for that once I have a nice selection for you to choose from.

Let's go!
